library(igraph)
setwd("../data")
read.csv("dwilson.edgelist.10.confidence.csv",header=FALSE)
g=graph.empty()+vertices(1:12)
dw<-read.csv("dwilson.edgelist.10.confidence.csv",header=FALSE)
g<-g+edges(as.vector(as.matrix(t(dw))))
plot(g)
dw_sigs<-read.csv("dw_signature_counts.csv", header=FALSE) 
plot(g,vertex.size=as.vector(t(dw_sigs))/3000)
