library(igraph)
#setwd("../data")
read.csv("combined.edgelist.20.confidence.csv",header=FALSE)
g=graph.empty()+vertices(1:25)
dw<-read.csv("combined.edgelist.20.confidence.csv",header=FALSE)
g<-g+edges(as.vector(as.matrix(t(dw))))
plot(g)
png("combined.edgelist.20.confidence.png")
plot(g)
dev.off()
#combined_sigs<-read.csv("combined_signature_counts.csv", header=FALSE) 
#plot(g,vertex.size=as.vector(t(dw_sigs))/3000)
